version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: leetcode_build
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: leetcode
    ports:
      - "5432:5432"
    volumes:
      - leetcode_db_data:/var/lib/postgresql/data

volumes:
  leetcode_db_data:
